# Data wrangling - La cirugia de los datos

El data wrangling a veces denominada data munging es el proceso de transformar y mapear datos de un dataset raw (en bruto) en otro formato con la intencion de hacerlo mas apropiado y valioso para una variedad de propositos posteriores, como el analisis. Una data wrangler es una persona que realiza estas operaciones de transformacion.
Esto puede incluir munging visualizacion de datos, agregacion de datos, entrenamiento de un modelo estadistico, asi como muchos otros usos potenciales. La oscilacion de datos como proceso generalmente sigue un conjunto de pasos generales que comienzan extrayendo los datos en forma cruda del origen de datos, dividiendo los datos en bruto usando algoritmos (por ejemplo clasificacion) o analizando los datos en estructuras de datos predefinidas y finalmente depositando el contenido resultante en un sistema de almacenamiento (o silo) para su futuro uso.

In [2]:
import pandas as pd

In [7]:
data = pd.read_csv("../datasets/customer-churn-model/Customer Churn Model.txt")

In [49]:
data.head()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.

### Crear un subconjunto de datos

In [16]:
# a veces solo necesitamos algunas columnas y no todas
account_len = data["Account Length"]

In [11]:
account_len.head()

0    128
1    107
2    137
3     84
4     75
Name: Account Length, dtype: int64

In [17]:
type(account_len)

pandas.core.series.Series

In [20]:
subset = data[["Account Length", "Phone", "Eve Charge", "Day Calls"]]

In [21]:
subset.head()

   Account Length     Phone  Eve Charge  Day Calls
0             128  382-4657       16.78        110
1             107  371-7191       16.62        123
2             137  358-1921       10.30        114
3              84  375-9999        5.26         71
4              75  330-6626       12.61        113

In [22]:
type(subset)

pandas.core.frame.DataFrame

In [25]:
desired_cols = ["Account Length", "Phone", "Eve Charge", "Night Calls"]

In [26]:
subset = data[desired_cols]
subset.head()

   Account Length     Phone  Eve Charge  Night Calls
0             128  382-4657       16.78           91
1             107  371-7191       16.62          103
2             137  358-1921       10.30          104
3              84  375-9999        5.26           89
4              75  330-6626       12.61          121

In [33]:
desired_cols = ["Account Length", "VMail Message", "Day Calls"]
desired_cols

['Account Length', 'VMail Message', 'Day Calls']

In [34]:
all_cols_list = data.columns.values.tolist()
all_cols_list

['State',
 'Account Length',
 'Area Code',
 'Phone',
 "Int'l Plan",
 'VMail Plan',
 'VMail Message',
 'Day Mins',
 'Day Calls',
 'Day Charge',
 'Eve Mins',
 'Eve Calls',
 'Eve Charge',
 'Night Mins',
 'Night Calls',
 'Night Charge',
 'Intl Mins',
 'Intl Calls',
 'Intl Charge',
 'CustServ Calls',
 'Churn?']

In [36]:
sublist = [x for x in all_cols_list if x not in desired_cols]
sublist

['State',
 'Area Code',
 'Phone',
 "Int'l Plan",
 'VMail Plan',
 'Day Mins',
 'Day Charge',
 'Eve Mins',
 'Eve Calls',
 'Eve Charge',
 'Night Mins',
 'Night Calls',
 'Night Charge',
 'Intl Mins',
 'Intl Calls',
 'Intl Charge',
 'CustServ Calls',
 'Churn?']

In [37]:
subset = data[sublist]
subset

,State,Area Code,Phone,Int'l Plan,VMail Plan,Day Mins,Day Charge,Eve Mins,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,415,382-4657,no,yes,265.1,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,415,371-7191,no,yes,161.6,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,415,358-1921,no,no,243.4,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,408,375-9999,yes,no,299.4,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,415,330-6626,yes,no,166.7,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.
5,AL,510,391-8027,yes,no,223.4,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False.
6,MA,510,355-9993,no,yes,218.2,37.09,348.5,108,29.62,212.6,118,9.57,7.5,7,2.03,3,False.
7,MO,415,329-9001,yes,no,157.0,26.69,103.1,94,8.76,211.8,96,9.53,7.1,6,1.92,0,False.
8,LA,408,335-4719,no,no,184.5,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False.
9,WV,415,330-8173,yes,yes,258.6,43.96,222.0,111,18.87,326.4,97,14.69,11.2,5,3.02,0,False.
10,IN,415,329-6603,no,no,129.1,21.95,228.5,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True.
11,RI,415,344-9403,no,no,187.7,31.91,163.4,148,13.89,196.0,94,8.82,9.1,5,2.46,0,False.
12,IA,408,363-1107,no,no,128.8,21.90,104.9,71,8.92,141.1,128,6.35,11.2,2,3.02,1,False.
13,MT,510,394-8006,no,no,156.6,26.62,247.6,75,21.05,192.3,115,8.65,12.3,5,3.32,3,False.
14,IA,415,366-9238,no,no,120.7,20.52,307.2,76,26.11,203.0,99,9.14,13.1,6,3.54,4,False.
15,NY,415,351-7269,no,no,332.9,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True.
16,ID,408,350-8884,no,yes,196.4,33.39,280.9,90,23.88,89.3,75,4.02,13.8,4,3.73,1,False.
17,VT,510,386-2923,no,no,190.7,32.42,218.2,111,18.55,129.6,121,5.83,8.1,3,2.19,3,False.
18,VA,510,356-2992,no,yes,189.7,32.25,212.8,65,18.09,165.7,108,7.46,10.0,5,2.70,1,False.
19,TX,415,373-2782,no,no,224.4,38.15,159.5,88,13.56,192.8,74,8.68,13.0,2,3.51,1,False.
20,FL,415,396-5800,no,no,155.1,26.37,239.7,93,20.37,208.8,133,9.40,10.6,4,2.86,0,False.
21,CO,408,393-7984,no,no,62.4,10.61,169.9,121,14.44,209.6,64,9.43,5.7,6,1.54,5,True.
22,AZ,415,358-1958,no,no,183.0,31.11,72.9,99,6.20,181.8,78,8.18,9.5,19,2.57,0,False.
23,SC,415,350-2565,no,no,110.4,18.77,137.3,102,11.67,189.6,105,8.53,7.7,6,2.08,2,False.
24,VA,510,343-4696,no,no,81.1,13.79,245.2,72,20.84,237.0,115,10.67,10.3,2,2.78,0,False.
25,NE,415,331-3698,no,no,124.3,21.13,277.1,112,23.55,250.7,115,11.28,15.5,5,4.19,3,False.
26,WY,408,357-3817,no,yes,213.0,36.21,191.1,112,16.24,182.7,115,8.22,9.5,3,2.57,0,False.
27,MT,408,418-6412,no,no,134.3,22.83,155.5,100,13.22,102.1,68,4.59,14.7,4,3.97,3,False.
28,MO,415,353-2630,no,no,190.0,32.30,258.2,84,21.95,181.5,102,8.17,6.3,6,1.70,0,False.
29,HI,510,410-7789,no,no,119.3,20.28,215.1,109,18.28,178.7,90,8.04,11.1,1,3.00,1,False.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3303,WI,415,373-7308,no,yes,137.1,23.31,155.7,125,13.23,247.6,94,11.14,11.5,7,3.11,2,False.
3304,IL,510,330-7137,yes,no,186.1,31.64,198.6,140,16.88,206.5,80,9.29,13.8,5,3.73,4,True.
3305,IN,415,406-8445,no,yes,224.1,38.10,238.8,85,20.30,174.2,86,7.84,11.5,7,3.11,2,False.
3306,AL,408,404-5283,no,yes,83.6,14.21,203.9,131,17.33,229.5,73,10.33,8.1,3,2.19,1,False.
3307,OK,408,398-3632,no,no,203.9,34.66,234.0,123,19.89,160.7,65,7.23,17.8,4,4.81,4,False.
3308,IA,415,399-5763,no,no,211.3,35.92,165.7,97,14.08,265.9,72,11.97,13.3,6,3.59,1,False.
3309,VT,408,340-9449,yes,no,219.4,37.30,225.7,102,19.18,255.3,95,11.49,12.0,4,3.24,4,False.
3310,NY,415,363-1123,no,no,190.4,32.37,92.0,107,7.82,224.8,108,10.12,13.6,17,3.67,2,False.
3311,LA,415,361-2170,no,no,147.7,25.11,283.3,83,24.08,188.3,124,8.47,6.9,5,1.86,2,False.
3312,SC,408,406-6304,no,no,229.9,39.08,144.4,93,12.27,262.4,110,11.81,14.2,4,3.83,2,False.
3313,ID,408,392-5090,no,no,102.8,17.48,143.7,95,12.21,191.4,97,8.61,10.0,5,2.70,1,False.
3314,MO,415,373-7713,no,no,178.7,30.38,233.7,74,19.86,131.9,120,5.94,9.1,4,2.46,1,False.
3315,ME,415,392-1376,no,yes,148.5,25.25,114.5,106,9.73,178.3,98,8.02,6.5,4,1.76,0,False.
3316,MS,510,390-6388,no,yes,164.1,27.90,219.1,96,18.62,220.3,108,9.91,12.3,9,3.32,0,False.
3317,SD,415,379-7290,yes,no,197.2,33.52,188.5,113,16.02,211.1,94,9.50,7.8,8,2.11,1,False.
3318,OK,415,397-9928,no,no,124.9,21.23,300.5,118,25.54,192.5,106,8.66,11.6,4,3.13,2,False.
3319,WY,415,378-6924,no,no,115.4,19.62,209.9,115,17.84,280.9,112,12.64,15.9,6,4.29,3,False.
3320,GA,510,411-5677,yes,no,140.0,23.80,196.4,77,16.69,120.1,133,5.40,9.7,4,2.62,4,True.
3321,VT,415,400-2738,no,no,193.9,32.96,85.0,110,7.23,210.1,134,9.45,13.2,8,3.56,3,False.
3322,MD,408,409-1856,no,no,321.1,54.59,265.5,122,22.57,180.5,72,8.12,11.5,2,3.11,4,True.
3323,IN,415,362-5899,no,no,118.4,20.13,249.3,97,21.19,227.0,56,10.22,13.6,3,3.67,5,True.
3324,WV,415,377-1164,no,no,169.8,28.87,197.7,105,16.80,193.7,82,8.72,11.6,4,3.13,1,False.
3325,OH,408,368-8555,no,no,193.4,32.88,116.9,88,9.94,243.3,109,10.95,9.3,4,2.51,2,False.
3326,OH,415,347-6812,no,no,106.6,18.12,284.8,87,24.21,178.9,92,8.05,14.9,7,4.02,1,False.
3327,SC,415,348-3830,no,no,134.7,22.90,189.7,68,16.12,221.4,128,9.96,11.8,5,3.19,2,False.
3328,AZ,415,414-4276,no,yes,156.2,26.55,215.5,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False.
3329,WV,415,370-3271,no,no,231.1,39.29,153.4,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False.
3330,RI,510,328-8230,no,no,180.8,30.74,288.8,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False.
3331,CT,510,364-6381,yes,no,213.8,36.35,159.6,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False.
3332,TN,415,400-4344,no,yes,234.4,39.85,265.9,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False.

In [39]:
a = set(desired_cols)
b = set(all_cols_list)
sublist = b - a
sublist

{'Area Code',
 'Churn?',
 'CustServ Calls',
 'Day Charge',
 'Day Mins',
 'Eve Calls',
 'Eve Charge',
 'Eve Mins',
 "Int'l Plan",
 'Intl Calls',
 'Intl Charge',
 'Intl Mins',
 'Night Calls',
 'Night Charge',
 'Night Mins',
 'Phone',
 'State',
 'VMail Plan'}

In [40]:
sublist = list(sublist)

In [41]:
sublist

['Area Code',
 'Phone',
 'Intl Mins',
 'Intl Charge',
 'Eve Charge',
 'Night Calls',
 'Intl Calls',
 'Churn?',
 'Eve Calls',
 'Day Mins',
 'Day Charge',
 'Night Charge',
 "Int'l Plan",
 'Eve Mins',
 'CustServ Calls',
 'Night Mins',
 'State',
 'VMail Plan']

## Filas con condiciones

In [43]:
data[10:25]

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
10,IN,65,415,329-6603,no,no,0,129.1,137,21.95,...,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True.
11,RI,74,415,344-9403,no,no,0,187.7,127,31.91,...,148,13.89,196.0,94,8.82,9.1,5,2.46,0,False.
12,IA,168,408,363-1107,no,no,0,128.8,96,21.90,...,71,8.92,141.1,128,6.35,11.2,2,3.02,1,False.
13,MT,95,510,394-8006,no,no,0,156.6,88,26.62,...,75,21.05,192.3,115,8.65,12.3,5,3.32,3,False.
14,IA,62,415,366-9238,no,no,0,120.7,70,20.52,...,76,26.11,203.0,99,9.14,13.1,6,3.54,4,False.
15,NY,161,415,351-7269,no,no,0,332.9,67,56.59,...,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True.
16,ID,85,408,350-8884,no,yes,27,196.4,139,33.39,...,90,23.88,89.3,75,4.02,13.8,4,3.73,1,False.
17,VT,93,510,386-2923,no,no,0,190.7,114,32.42,...,111,18.55,129.6,121,5.83,8.1,3,2.19,3,False.
18,VA,76,510,356-2992,no,yes,33,189.7,66,32.25,...,65,18.09,165.7,108,7.46,10.0,5,2.70,1,False.
19,TX,73,415,373-2782,no,no,0,224.4,90,38.15,...,88,13.56,192.8,74,8.68,13.0,2,3.51,1,False.
20,FL,147,415,396-5800,no,no,0,155.1,117,26.37,...,93,20.37,208.8,133,9.40,10.6,4,2.86,0,False.
21,CO,77,408,393-7984,no,no,0,62.4,89,10.61,...,121,14.44,209.6,64,9.43,5.7,6,1.54,5,True.
22,AZ,130,415,358-1958,no,no,0,183.0,112,31.11,...,99,6.20,181.8,78,8.18,9.5,19,2.57,0,False.
23,SC,111,415,350-2565,no,no,0,110.4,103,18.77,...,102,11.67,189.6,105,8.53,7.7,6,2.08,2,False.
24,VA,132,510,343-4696,no,no,0,81.1,86,13.79,...,72,20.84,237.0,115,10.67,10.3,2,2.78,0,False.

In [47]:
data[:8]

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.
5,AL,118,510,391-8027,yes,no,0,223.4,98,37.98,...,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False.
6,MA,121,510,355-9993,no,yes,24,218.2,88,37.09,...,108,29.62,212.6,118,9.57,7.5,7,2.03,3,False.
7,MO,147,415,329-9001,yes,no,0,157.0,79,26.69,...,94,8.76,211.8,96,9.53,7.1,6,1.92,0,False.

In [50]:
data[3320:]

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
3320,GA,122,510,411-5677,yes,no,0,140.0,101,23.80,...,77,16.69,120.1,133,5.40,9.7,4,2.62,4,True.
3321,VT,60,415,400-2738,no,no,0,193.9,118,32.96,...,110,7.23,210.1,134,9.45,13.2,8,3.56,3,False.
3322,MD,62,408,409-1856,no,no,0,321.1,105,54.59,...,122,22.57,180.5,72,8.12,11.5,2,3.11,4,True.
3323,IN,117,415,362-5899,no,no,0,118.4,126,20.13,...,97,21.19,227.0,56,10.22,13.6,3,3.67,5,True.
3324,WV,159,415,377-1164,no,no,0,169.8,114,28.87,...,105,16.80,193.7,82,8.72,11.6,4,3.13,1,False.
3325,OH,78,408,368-8555,no,no,0,193.4,99,32.88,...,88,9.94,243.3,109,10.95,9.3,4,2.51,2,False.
3326,OH,96,415,347-6812,no,no,0,106.6,128,18.12,...,87,24.21,178.9,92,8.05,14.9,7,4.02,1,False.
3327,SC,79,415,348-3830,no,no,0,134.7,98,22.90,...,68,16.12,221.4,128,9.96,11.8,5,3.19,2,False.
3328,AZ,192,415,414-4276,no,yes,36,156.2,77,26.55,...,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False.
3329,WV,68,415,370-3271,no,no,0,231.1,57,39.29,...,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False.
3330,RI,28,510,328-8230,no,no,0,180.8,109,30.74,...,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False.
3331,CT,184,510,364-6381,yes,no,0,213.8,105,36.35,...,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False.
3332,TN,74,415,400-4344,no,yes,25,234.4,113,39.85,...,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False.

In [53]:
# usuarios con total Mins > 500
data1 = data[data["Day Mins"]>300]
data1

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
15,NY,161,415,351-7269,no,no,0,332.9,67,56.59,...,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True.
76,DC,82,415,374-5353,no,no,0,300.3,109,51.05,...,100,15.39,270.1,73,12.15,11.7,4,3.16,0,True.
156,OH,83,415,370-9116,no,no,0,337.4,120,57.36,...,116,19.33,153.9,114,6.93,15.8,7,4.27,0,True.
197,TX,208,510,378-3625,no,no,0,326.5,67,55.51,...,113,14.99,181.7,102,8.18,10.7,6,2.89,2,True.
230,MD,93,408,360-3324,yes,no,0,312.0,109,53.04,...,100,11.00,217.6,74,9.79,10.5,2,2.84,0,True.
289,OK,89,510,352-6976,no,no,0,303.9,95,51.66,...,114,22.18,312.1,89,14.04,5.3,3,1.43,1,True.
365,CO,154,415,343-5709,no,no,0,350.8,75,59.64,...,94,18.40,253.9,100,11.43,10.1,9,2.73,1,True.
534,LA,67,510,373-6784,no,no,0,310.4,97,52.77,...,123,5.65,246.5,99,11.09,9.2,10,2.48,4,False.
575,SD,114,415,351-7369,no,yes,36,309.9,90,52.68,...,89,17.03,183.5,105,8.26,14.2,2,3.83,1,False.
605,MO,112,415,373-2053,no,no,0,335.5,77,57.04,...,109,18.06,265.0,132,11.93,12.7,8,3.43,2,True.
688,MN,13,510,338-7120,no,yes,21,315.6,105,53.65,...,71,17.76,260.1,123,11.70,12.1,3,3.27,3,False.
732,IN,48,510,342-6696,no,no,0,300.4,94,51.07,...,103,11.32,197.4,94,8.88,7.2,5,1.94,2,False.
815,KY,75,415,341-1191,no,no,0,314.6,102,53.48,...,86,14.43,285.1,100,12.83,5.7,3,1.54,2,True.
832,SC,87,408,335-1874,no,no,0,322.5,106,54.83,...,93,17.39,186.2,128,8.38,9.4,4,2.54,2,True.
901,CT,23,510,370-5527,no,no,0,321.6,107,54.67,...,115,21.39,141.1,158,6.35,11.3,3,3.05,2,True.
975,DE,129,510,332-6181,no,no,0,334.3,118,56.83,...,104,16.33,191.0,83,8.59,10.4,6,2.81,0,True.
985,NY,64,415,345-9140,yes,no,0,346.8,55,58.96,...,79,21.21,275.4,102,12.39,13.3,9,3.59,1,True.
1078,ME,80,408,333-7631,no,no,0,322.3,113,54.79,...,95,18.87,162.8,123,7.33,6.7,8,1.81,0,True.
1165,VT,50,415,387-5891,yes,yes,26,307.1,94,52.21,...,78,24.60,174.9,109,7.87,8.0,3,2.16,0,False.
1334,KS,126,408,379-8681,no,no,0,321.3,99,54.62,...,93,14.27,193.6,106,8.71,8.0,4,2.16,1,True.
1355,TX,50,408,330-6436,no,yes,31,302.7,93,51.46,...,119,20.44,193.9,103,8.73,13.6,14,3.67,3,False.
1679,OK,82,510,393-4823,no,no,0,329.8,73,56.07,...,120,17.71,267.1,102,12.02,10.6,6,2.86,0,True.
1830,CT,50,408,351-9037,no,no,0,301.7,82,51.29,...,118,14.20,72.2,89,3.25,10.5,6,2.84,1,False.
2028,SD,93,510,408-4836,no,no,0,328.1,106,55.78,...,89,12.89,303.5,114,13.66,8.7,3,2.35,1,True.
2215,MS,13,415,413-7468,no,no,0,303.2,133,51.54,...,86,14.49,227.6,80,10.24,11.5,3,3.11,0,True.
2259,NC,210,415,363-7802,no,yes,31,313.8,87,53.35,...,103,12.55,192.7,97,8.67,10.1,7,2.73,3,False.
2267,MS,29,510,401-6982,no,no,0,313.2,103,53.24,...,151,18.39,218.4,106,9.83,12.8,4,3.46,2,True.
2376,NV,42,415,352-5466,no,no,0,303.9,106,51.66,...,54,19.74,147.1,76,6.62,5.8,3,1.57,1,True.
2412,WI,89,415,373-4264,no,no,0,326.3,112,55.47,...,110,14.03,162.9,97,7.33,7.5,1,2.03,1,True.
2478,TN,123,415,415-3016,no,yes,34,305.2,80,51.88,...,109,13.30,280.0,81,12.60,13.2,7,3.56,1,False.
2572,MN,152,415,378-9542,no,no,0,317.8,60,54.03,...,100,13.00,123.4,63,5.55,10.4,7,2.81,1,True.
2573,WV,124,415,344-1970,no,no,0,312.0,112,53.04,...,109,15.30,168.6,94,7.59,12.8,4,3.46,1,True.
2594,OH,115,510,348-1163,yes,no,0,345.3,81,58.70,...,106,17.29,217.5,107,9.79,11.8,8,3.19,1,True.
2629,NH,141,415,402-3370,no,yes,32,322.4,92,54.81,...,107,24.07,209.5,111,9.43,6.7,3,1.81,1,True.
2660,NJ,88,415,347-8659,no,no,0,301.5,136,51.26,...,72,21.90,132.9,118,5.98,13.4,2,3.62,4,True.
2677,IA,44,415,359-7426,no,no,0,308.6,139,52.46,...,94,12.82,198.7,66,8.94,7.3,3,1.97,4,True.
2696,MI,74,415,359-6232,no,no,0,314.1,86,53.40,...,99,18.90,259.0,121,11.66,12.3,5,3.32,3,True.
2824,OR,81,415,406-4100,no,no,0,324.7,48,55.20,...,82,20.09,187.6,78,8.44,13.1,5,3.54,0,True.
2858,AL,141,510,388-8583,no,yes,28,308.0,123,52.36,...,128,21.06,152.9,103,6.88,7.4,3,2.00,1,False.
3072,TX,75,415,417-4456,no,no,0,305.1,106,51.87,...,115,15.98,235.4,116,10.59,8.5,5,2.30,0,True.
3132,NC,161,415,394-5489,no,no,0,322.3,100,54.79,...,135,19.58,241.5,104,10.87,7.8,5,2.11,2,True.
3207,DC,93,408,345-1994,no,yes,22,306.2,123,52.05,...,83,16.12,240.3,107,10.81,11.7,2,3.16,0,False.
3322,MD,62,408,409-1856,no,no,0,321.1,105,54.59,...,122,22.57,180.5,72,8.12,11.5,2,3.11,4,True.

In [61]:
## Usuarios de New York
data2 = data[data["State"]=="NY"]
data2.shape

(83, 21)

In [56]:
## and -> 
data3 = data[(data["Day Mins"]>300) & (data["State"]=="NY")]
data3

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
15,NY,161,415,351-7269,no,no,0,332.9,67,56.59,...,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True.
985,NY,64,415,345-9140,yes,no,0,346.8,55,58.96,...,79,21.21,275.4,102,12.39,13.3,9,3.59,1,True.

In [57]:
# or -> |
data4 = data[ (data["Day Mins"]>300) | (data["State"]=="NY")]
data4.shape

(124, 21)

In [60]:
data5 = data[data["Day Calls"] < data["Night Calls"]]
data5.shape

(1626, 21)

In [63]:
data6 = data[data["Day Mins"] < data["Night Mins"]]
data6.shape

(2051, 21)

## Subconjuntos con loc iloc y creacion de nuevas columnas

In [68]:
# Minutos de dia de noche y longitud de la cuenta de los primeros 50 individuos
# dos filtros so dos corchetes 1 para columnas y el 2 para las filas
subset_first_50 = data[["Day Mins", "Night Mins", "Account Length"]][:50]
subset_first_50.head()

   Day Mins  Night Mins  Account Length
0     265.1       244.7             128
1     161.6       254.4             107
2     243.4       162.6             137
3     299.4       196.9              84
4     166.7       186.9              75

In [69]:
#Indice ix 1 fila 2 columna
data.ix[:10, 3:6]

/home/karen/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

       Phone Int'l Plan VMail Plan
0   382-4657         no        yes
1   371-7191         no        yes
2   358-1921         no         no
3   375-9999        yes         no
4   330-6626        yes         no
5   391-8027        yes         no
6   355-9993         no        yes
7   329-9001        yes         no
8   335-4719         no         no
9   330-8173        yes        yes
10  329-6603         no         no

In [70]:
data.iloc[1:10, 3:6]

      Phone Int'l Plan VMail Plan
1  371-7191         no        yes
2  358-1921         no         no
3  375-9999        yes         no
4  330-6626        yes         no
5  391-8027        yes         no
6  355-9993         no        yes
7  329-9001        yes         no
8  335-4719         no         no
9  330-8173        yes        yes

In [71]:
data.iloc[:, 3:6] #Todas las filas para las columnas entre la 3 y 6
data.iloc[1:10, :]

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.
5,AL,118,510,391-8027,yes,no,0,223.4,98,37.98,...,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False.
6,MA,121,510,355-9993,no,yes,24,218.2,88,37.09,...,108,29.62,212.6,118,9.57,7.5,7,2.03,3,False.
7,MO,147,415,329-9001,yes,no,0,157.0,79,26.69,...,94,8.76,211.8,96,9.53,7.1,6,1.92,0,False.
8,LA,117,408,335-4719,no,no,0,184.5,97,31.37,...,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False.
9,WV,141,415,330-8173,yes,yes,37,258.6,84,43.96,...,111,18.87,326.4,97,14.69,11.2,5,3.02,0,False.

In [72]:
data.iloc[1:10, [2,5,7]]

   Area Code VMail Plan  Day Mins
1        415        yes     161.6
2        415         no     243.4
3        408         no     299.4
4        415         no     166.7
5        510         no     223.4
6        510        yes     218.2
7        415         no     157.0
8        408         no     184.5
9        415        yes     258.6

In [73]:
data.iloc[[1,5,8,36], [2,5,7]]

    Area Code VMail Plan  Day Mins
1         415        yes     161.6
5         510         no     223.4
8         408         no     184.5
36        408        yes     146.3

In [74]:
data.loc[[1,5,8,36], ["Area Code", "WMail Plan", "Day Mins"]]

/home/karen/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1494: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)

    Area Code  WMail Plan  Day Mins
1         415         NaN     161.6
5         510         NaN     223.4
8         408         NaN     184.5
36        408         NaN     146.3

In [75]:
data["Total Mins"]= data["Day Mins"]+data["Night Mins"]+ data["Eve Mins"]

In [78]:
data["Total Mins"].head()

0    707.2
1    611.5
2    527.2
3    558.2
4    501.9
Name: Total Mins, dtype: float64

In [79]:
data.head()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?,Total Mins
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,16.78,244.7,91,11.01,10.0,3,2.70,1,False.,707.2
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,16.62,254.4,103,11.45,13.7,3,3.70,1,False.,611.5
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,10.30,162.6,104,7.32,12.2,5,3.29,0,False.,527.2
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,5.26,196.9,89,8.86,6.6,7,1.78,2,False.,558.2
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,12.61,186.9,121,8.41,10.1,3,2.73,3,False.,501.9

In [80]:
data["Total Calls"] = data["Day Calls"]+data["Night Calls"]+ data["Eve Calls"]

In [81]:
data.head()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?,Total Mins,Total Calls
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,244.7,91,11.01,10.0,3,2.70,1,False.,707.2,300
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,254.4,103,11.45,13.7,3,3.70,1,False.,611.5,329
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,162.6,104,7.32,12.2,5,3.29,0,False.,527.2,328
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,196.9,89,8.86,6.6,7,1.78,2,False.,558.2,248
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,186.9,121,8.41,10.1,3,2.73,3,False.,501.9,356

In [82]:
data.shape

(3333, 23)

## Generacion de numeros aleatorios

In [83]:
import numpy as np

In [89]:
#generar un numero aleatorio entre 1 y 100
np.random.randint(1,100)

77

In [93]:
# la forma mas clasica de generar un numero aleatoria es entre 0 y 1 con decimales
np.random.random()

0.44594848331360537

In [94]:
range(1,8)

range(1, 8)

In [95]:
## funcion que genera una lista de n numeros aleatorios enteros dentro del intervalo a,b
def randint_list(n, a, b):
    x = []
    for i in range(n):
        x.append(np.random.randint(a,b))
    return x

In [97]:
randint_list(25, 1,50)

[2,
 32,
 19,
 7,
 27,
 5,
 7,
 48,
 38,
 38,
 9,
 19,
 32,
 27,
 35,
 1,
 27,
 43,
 17,
 19,
 22,
 44,
 44,
 19,
 43]

In [98]:
import random

In [112]:
random.randrange(1, 100,7)

43

### Shuffling
barajar

In [114]:
a = np.arange(100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [115]:
np.random.shuffle(a)

In [116]:
a

array([65, 84, 14,  5, 87, 66, 79, 74,  6, 38, 48,  2,  3, 62, 52, 24, 18,
       94, 57, 59, 41, 10, 89, 45, 26, 98, 83, 31, 42,  0, 27, 40, 88, 73,
       16, 54, 28,  7, 19, 76, 71, 78, 33, 15, 82, 70, 67, 96, 93, 58, 81,
        1, 22, 44, 64, 53, 61, 29, 90, 43, 92, 37, 50, 13, 17, 80,  4, 60,
       97, 36, 21, 72, 99, 77, 12, 39, 34, 55, 30, 46, 51, 56, 47, 91, 49,
       20, 68,  8, 11, 23,  9, 32, 85, 69, 35, 95, 25, 75, 63, 86])

### Choice

In [117]:
column_list = data.columns.values.tolist()
column_list

['State',
 'Account Length',
 'Area Code',
 'Phone',
 "Int'l Plan",
 'VMail Plan',
 'VMail Message',
 'Day Mins',
 'Day Calls',
 'Day Charge',
 'Eve Mins',
 'Eve Calls',
 'Eve Charge',
 'Night Mins',
 'Night Calls',
 'Night Charge',
 'Intl Mins',
 'Intl Calls',
 'Intl Charge',
 'CustServ Calls',
 'Churn?',
 'Total Mins',
 'Total Calls']

In [120]:
np.random.choice(column_list)

'State'

### Seed

In [123]:
np.random.seed(2018)
for i in range(5):
    print(np.random.random())

0.8823493117539459
0.10432773786047767
0.9070093335163405
0.3063988986063515
0.446408872427422